== MyGourmet Fullstack Spring - JSF, Spring, Orchestra and JPA combined (pending)

In this chapter, we will use our MyGourmet example to introduce the architecture of a Spring JSF application that has proven itself in practice in this or similar form. 
It provides an optimal starting point for your own JSF web applications - even for more complex applications. 
The example MyGourmet Fullstack Spring is an extension of the example MyGourmet 16 Spring, in which on the one hand the functionality of the application is expanded and on the other hand the architecture of the application is brought to the current state of the technology. 

By default, Apache MyFaces comes as a JSF implementation for use. 
The example also works with the current version of Mojarra. 
As in all other examples, you can also define the JSF implementation via a profile in the `pom.xml` file (see Appendix Chapter: A Brief Introduction to Maven for details). 
In Spring is as persistence Java Persistence API (JPA) in version 2.0 with the Hibernate Entity used as implementation. 
On the database side, HyperSQL Data-Base (HSQLDB) is available - but any database supported by Hibernate can be used. 

The source code too MyGourmet Fullstack can be found like the code of all previous examples at http://jsfatwork.irian.at.

=== Architecture of MyGourmet Fullstack

In MyGourmet Fullstack, Java architecture is widely used with three superimposed layers. 
The presentation layer is the top layer and includes the user interface. 
It accesses the service layer in which the business logic of the application is defined. 
At the bottom is the data access layer, which encapsulates all access to the application data in the service layer. 
The entities behind the model behind the application are available across layers. 
Figure architecture of MyGourmet Fullstack Spring shows a graphic representation of the architecture of MyGourmet Fullstack Spring.
 
Figure: Architecture of MyGourmet Fullstack Spring

An advantage of the layered architecture is the strict separation of responsibilities (SOC). 
Each layer is responsible for a specific area of ​​the application. 
A layer can access the functionality of the layer directly under it and can offer functionality to the layer directly above it. 
Since there must never be any dependencies upwards, each layer with its underlying layers forms a closed subsystem. 

We recommend that you always adhere to a clean delineation - even if at first glance it looks like an unnecessary extra effort. 
The separation (of course only in reasonable places) pays off at the latest in the maintenance. 

In the next sections we will take a quick look at all layers of MyGourmet Fullstack Spring including the cross-layer entities throw. The structure of the Maven project is a bit simpler and does not directly correspond to the layers of the application. 
For the sake of simplicity, we have summarized the entities, the data access layer, and the service layer in the mygourmet-service-spring module. 
The presentation layer is in the module mygourmet-webapp-spring. But for larger projects, it makes sense to house each layer in its own Maven module.

==== Entities

Entities make up the model of business objects and are a central component of any application. 
Entities are simple JavaBeans with properties and their getter and setter methods. 
They represent the object-oriented representation of the tables in the database. 
Because they are used in all layers, they are located outside the layers from an architectural perspective. 
The entity classes can be found in the package at.irian.jsfatwork.domain in the module mygourmet-service-spring.

The information about the mapping between the tables and columns of the database and the entities and properties is contained directly in the classes. 
JPA offers a number of annotations. This eliminates the need to create tons of XML files to configure this mapping. 

The custom bean validation validators must also be in the mygourmet-service-spring module as they are used in the entities. But since bean validation is not dependent on JSF, this is not a problem. 
You can find the validator classes and annotations in at.irian.jsfatwork.validation.

==== Data access layer

In the data access layer, the interface to the database is realized with a generic crud service. 
This service is implemented in the CrudService class as a Spring bean in the singleton scope and uses Spring's JPA support. 
The Crud service provides generic methods for the key features of JPA's Entity Manager. 
For MyGourmet, this simple implementation is enough - in more complex applications such a crud service can serve as a basis for repositories, for example. Listing MyGourmet Fullstack Spring: CrudService shows parts of the CrudService class.

@Named("crudService")
@Singleton
public class CrudService {

  @PersistenceContext(unitName = "mygourmet")
  private EntityManager em;

  public <T extends BaseEntity> void persist(T entity) {
    em.persist(entity);
  }
  public <T extends BaseEntity> T findById(
      Class<T> clazz, long id) {
    return em.find(clazz, id);
  }
  public <T extends BaseEntity> void delete(T entity) {
    em.remove(entity);
  }
}

The central place to interact with the persistence context of JPA is the EntityManager class. 
In MyGourmet, the Entity Manager is configured through Spring and managed by Orchestra. 
Spring evaluates the annotation @PersistenceContext and sets the Entity Manager to the annotated property when creating the Bean CrudService. 

Orchestra ensures that Spring uses the persistence context of the current conversation. 
If You List MyGourmet Fullstack Spring: CrudService Looking again, you will notice that the bean is defined in the singleton scope. 
However, the persistence context is tied to a shorter-lived conversation. 
How can this work? The Spring injected entity manager is a proxy that governs access to the current persistence context. 

With the persistence support of Orchestra, the Crud service runs in the context of the current conversation. 
They are injected with the same entity manager that is created at the beginning of the conversation and kept open until the end. 
That's what it's like with Orchestra also possible without problems to work directly with the entities within a conversation. 
Exceptions caused by a short-lived persistence context are a thing of the past. 

The configuration of JPA will be discussed later in section [Section: Configuration of JPA].

==== Service layer

The business logic of the application resides in the service layer and is decoupled from the user interface. 
The service layer is injected with the Crud service and calls it up when needed, such as during a persistence. 
The way to the database should be in the presentation layer only through the service layer and not directly through the data access layer. 

In the package at.irian.jsfatwork.service there is an interface for each service bean. 
The corresponding implementation is in the subpackage impl, This ensures that it is possible to program against the interface and that concrete implementation details are hidden from the application when accessing the services. 
The implementation classes are defined by the JSR 330 annotation @Named as Spring beans in the singleton scope. 
Listing MyGourmet Fullstack Spring: Service implementation exemplifies the ProviderServiceImpl class.

@Named("providerService")
@Singleton
public class ProviderServiceImpl implements ProviderService {
  @Inject
  private CrudService crudService;

  public Provider createNew() {
    return crudService.createNew(Provider.class);
  }
  @Transactional
  public void save(Provider entity) {
    crudService.persist(entity);
  }
  @Transactional
  public void delete(Provider provider) {
    for (Order order : provider.getOrders()) {
      order.setCustomer(null);
      crudService.delete(order);
    }
    provider.getCategories().clear();
    crudService.delete(provider);
  }
  @Transactional(readOnly = true)
  public Provider findById(long id) {
    return crudService.findById(Provider.class, id);
  }
  @Transactional(readOnly = true)
  public List<Provider> findAll() {
    return crudService.findAll(Provider.class);
  }
}

The service layer in MyGourmet Fullstack Spring is also responsible for the transaction control of the application. 
The transactions are targeted to individual service methods and are managed by Spring. 
Each method of a service class annotated @Transactional is executed in a transaction. 
The service layer is the ideal place to define transactions because it represents the gateway to business logic for the user interface. 
If you take another look at Listing MyGourmet Fullstack Spring: CrudService, you will notice that there is no @TransactionalAnnotations exist. 
After crud operations are only used in the service, they automatically expire in the transactions defined there. 

For example, delamination is also extremely important for testing. 
The application can then be tested directly (without running the GUI itself) via the service layer. 
We recommend that you test the service layer from the beginning and keep the tests consistent with the GUI logic. 
Especially in the development of web applications, any failure to restart the server that could have been prevented by running a test costs valuable development time.

==== Presentation Layer

The presentation layer includes the user interface of the application and forms the top layer of the architecture. 
In MyGourmet Fullstack Spring, the presentation layer consists of the JSF web application and is housed in the Maven module mygourmet-webapp-spring. 
This module contains all page declarations and their view controllers as well as all components, converters, validators and phase listeners.

The presentation layer is only responsible for the user interface and accesses the service layer to execute business logic. Conversely, there must be no dependencies on the service layer or even the data access layer on the presentation layer. 
Of course, GUI / JSF specifics have not lost anything there. Attentive readers will now note that we discussed the role of Orchestra in managing the persistence context in Section [Data Access Layer], on the Data Access Layer. 
Have we already violated the principle of delamination here? The answer is no, because Orchestra manages the persistence context out of the presentation layer.

Let's take a closer look at this process using the customer overview page and its view controller. 
Listing MyGourmet Fullstack Spring: View Controller on the Customer Overview page shows the CustomerListBean class of the View controller. 
Initial access to the view creates the bean customerListBean, including the conversation of the same name with the persistence context. 
From this point, Orchestra ensures that Spring uses the persistence context associated with the conversation. 
When loading the customer list in the method preRenderView, when calling customerService.findAll () the persistence context of the conversation is already being used in the underlying crud service.

@Named("customerListBean")
@Scope("access")
@ViewController(viewIds = {"/customerList.xhtml"})
public class CustomerListBean {
  @Inject
  private CustomerService customerService;
  private List<Customer> customerList;

  @PreRenderView
  public void preRenderView() {
    customerList = customerService.findAll();
  }
  public List<Customer> getCustomerList() {
    return customerList;
  }
  public String deleteCustomer(Customer customer) {
    customerService.delete(customer);
    return null;
  }
}

The same applies to deleting a customer in deleteCustomer. 
When calling customerService.delete (customer), the persistence context of the conversation is also used in the underlying crud service. When the action method is called, the customer to be deleted is transferred directly via the method expression as one of the previously loaded entities. 
The persistence context tied to the conversation also makes this possible without problems. 
After the method delete is annotated in the service with @Transactional, the operation even takes place in a transaction. 

The automatic management of the persistence context by Orchestra Of course, this only works for managed beans in Access or Manual Scope.

=== Configuration of the application

The configuration of MyGourmet Fullstack Spring largely corresponds to the already known configuration from the previous examples. 
New are only the settings for JPA and the persistence support of Orchestra. 
Therefore, we will not go into the basic configuration in this section. 

In the first step, we also adapted the Spring configuration to the new structure of the Maven project. 
There is now a configuration file for each Maven module:

service.spring.xml in the module mygourmet-service-spring

web.spring.xml in the module mygourmet-webapp-spring

Listing MyGourmet Fullstack Spring: Configuring Spring in the web.xml shows the contextConfigLocation parameter with the names of the configuration files in the web.xml. 
The configuration file service.spring.xml comes from the classpath, because the service module is defined as a maven dependency in the webapp module.

<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>
    /WEB-INF/web.spring.xml
    classpath:service.spring.xml
  </param-value>
</context-param>

In section [Section: Configuration of JPA] we will briefly discuss the details of the configuration of JPA in Spring in the service.spring.xml file. 
This is followed by section [Section: Configuring Orchestra ] for more information about configuring Orchestra's persistence support in web.spring.xml.

==== Configuration of JPA

In this section we will introduce you to some details of the configuration file service.spring.xml with the settings for JPA under Spring. 
We chose the Hibernate EntityManager as an implementation of JPA 2.0. 
The database uses HyperSQL DataBase (HSQLDB). 

First, a data source must be defined for the database. 
This is best done with a connection pool, in our case C3P0. 
Listing MyGourmet Fullstack Spring: Configuration of the Entity Manager Factory shows the definition of the bean dataSource with the settings for the database and the connection pool.

<!-- Configure a c3p0 pooled data source -->
<bean id="dataSource" class="com.mchange.v2.c3p0
    .ComboPooledDataSource">
  <property name="user" value="sa"/>
  <property name="password" value=""/>
  <property name="driverClass" value="org.hsqldb.jdbcDriver"/>
  <property name="jdbcUrl" value="jdbc:hsqldb:mem:."/>
  <property name="initialPoolSize" value="1"/>
  <property name="minPoolSize" value="1"/>
  <property name="maxPoolSize" value="10"/>
</bean>
<!-- Hibernate JPA entity manager factory -->
<bean id="entityManagerFactory"
    class="org.springframework.orm.jpa
        .LocalContainerEntityManagerFactoryBean">
  <property name="dataSource" ref="dataSource"/>
  <property name="jpaVendorAdapter">
    <bean class="org.springframework.orm.jpa.vendor
        .HibernateJpaVendorAdapter">
      <property name="showSql" value="false"/>
      <property name="database" value="HSQL"/>
      <property name="generateDdl" value="true"/>
    </bean>
  </property>
  <property name="persistenceUnitName" value="mygourmet"/>
</bean>

The focal point of JPA's configuration in Spring is the definition of entity manager factory. 
For example, this factory is used to create the entity manager that is used in the crud service bean. 
In our example, the factory is defined in the Bean entityManagerFactory (see Listing MyGourmet Fullstack Spring: Configuring the Entity Manager Factory ). 
In the property dataSource we set the previously defined data source and in the property jpaVendorAdapter follow details about the chosen JPA implementation. 
For Hibernate comes a bean of the class HibernateJpaVendorAdapter for use. 
This bean gets the type of database used in the database property. 
By setting the property generateDdl to true we have Hibernate on to create the database from the mappings. 

For Spring to properly handle the annotation @PersistenceContext to inject the entity manager in the crud service, the <context: annotation-config /> element must be added to the configuration. 

In MyGourmet, transaction control is realized declaratively with the annotation @Transactional. 
@Transactional can be applied to interfaces, classes and methods with public visibility. 
However, Spring recommends annotating only concrete classes to avoid problems with proxies. 
The annotations themselves, however, are not enough to start transactions. 
Spring still has to be instructed to do the transaction control based on the annotations with the tag tx: annotation-driven. 
The required transaction manager is specified in the attribute transaction-manager of the tag. 
In our case, this is a special transaction manager for JPA. 
Listing MyGourmet Fullstack Spring: Configuring Transaction Control shows the configuration of the transaction control.

<tx:annotation-driven
    transaction-manager="transactionManager"/>

<bean id="transactionManager"
    class="org.springframework.orm.jpa.JpaTransactionManager">
  <property name="entityManagerFactory"
      ref="entityManagerFactory"/>
</bean>

==== Configuring Orchestra

With the configuration of JPA shown in the last section, we can extend the basic configuration of Orchestra for persistence support described in section Section: Configuring Orchestra. 
The complete configuration can be found in the configuration file web.spring.xml in the module mygourmet-webapp-spring. 
In order for the persistence context to bind to the conversation, the conversation scopes must be extended by an interceptor. 
For this purpose, an AOP Advice is added in the bean definition via the property advices, which checks whether the right persistence context is set each time a bean is accessed in the conversation. listing 

MyGourmet Fullstack Spring: Configuration of Persation Support Conversation Scopes shows how to configure the Access and Manual Scopes with the Interceptor.

<bean class="org.springframework.beans.factory.config
    .CustomScopeConfigurer">
  <property name="scopes">
    <map>
      <entry key="manual">
        <bean class="org.apache.myfaces.orchestra
            .conversation.spring.SpringConversationScope">
          <property name="timeout" value="30"/>
          <property name="lifetime" value="manual"/>
          <property name="advices">
            <list><ref bean="persistentContextInterceptor"/>
            </list>
          </property>
        </bean>
      </entry>
      <entry key="access">
        <bean class="org.apache.myfaces.orchestra
            .conversation.spring.SpringConversationScope">
          <property name="timeout" value="30"/>
          <property name="lifetime" value="access"/>
          <property name="advices">
            <list><ref bean="persistentContextInterceptor"/>
            </list>
          </property>
        </bean>
      </entry>
    </map>
  </property>
</bean>

The bean persistentContextInterceptor is the interceptor for the scopes and ensures that the right persistence context is always used. 
The interceptor needs a suitable factory for the persistence technology used, which is set via the property persistenceContextFactory. 
For JPA, Orchestra already comes with a finished factory that expects a fully configured JPA entity manager factory to be created in the entityManagerFactory property to create the persistence context. 
With the configuration of the Entity Manager Factory, we leave Orchestra and immerse ourselves in the world of JPA. How this works, we have already seen in the last section. 
listing MyGourmet Fullstack Spring: Configuring persistence support in Orchestra shows how to configure persistence support in Orchestra.

<bean id="persistentContextInterceptor"
    class="org.apache.myfaces.orchestra.conversation
    .spring.PersistenceContextConversationInterceptor">
  <property name="persistenceContextFactory"
      ref="persistentContextFactory"/>
</bean>
<bean id="persistentContextFactory"
    class="org.apache.myfaces.orchestra.conversation
    .spring.JpaPersistenceContextFactory">
  <property name="entityManagerFactory"
      ref="entityManagerFactory"/>
</bean>

MyGourmet Fullstack Spring is now fully configured and ready for use. 
We invite you to take a close look at the source code of the application. 
Consider the example as the basis for your own experiments and explore the details of the collaboration between JSF, JPA, Spring and Orchestra in practice.