== Tobago - JSF and more (pending)
There are a variety of frameworks available for developing web applications using the JSF standard. These frameworks usually provide controls and other features for designing the front end of an application. One of these frameworks is called Tobago , which we will discuss in more detail below.
=== Tobago - an overview
The development of Tobago started in 2002. Since 2005, Tobago has been an open source project and, like the Trinidad framework in 2006, became a subproject of the Apache MyFaces project. 
Tobago provides a convenient way to build web applications based on advanced JSF controls. In contrast to other frameworks, the positioning of the individual controls is controlled by a layout manager, which will be discussed in more detail later. 
But Tobago is more than just a component library based on the JSF standard. The focus of Tobago Rather, it's about creating business applications without the direct use of HTML, CSS, and JavaScript. In addition, a Tobago page description follows more of the development of a desktop user interface than a web page. A page description in Tobago does not need any HTML, so it does not need the typical HTML framework of DIV tags to position the controls on the page. 
The design and the styles are regulated in Tobago via CSS. Currently, Tobago only supports themes for HTML / CSS clients (renderers for WML and XSL: FO provide a proof of concept) group). In order to achieve a certain independence, HTML, CSS or JavaScript should not be used in the page description. A page description in Tobago usually only contains Tobago and JSF tags. 
The Tobago project is available at http://myfaces.apache.org/tobago/ and offers the following in addition to further documentation:
Control overview The demonstration introduces existing controls and their handling or configuration options. http://people.apache.org/repo/m2-snapshot-repository/org/apache/myfaces/tobago/tobago-example-demo/
Address Book Application The Address Book is a small, self-contained application that shows how to use Tobago in a more complex environment. http://people.apache.org/repo/m2-snapshot-repository/org/apache/myfaces/tobago/tobago-example-addressbook/
Basic Setup The Basic Setup can be used as an initial project setup. http://people.apache.org/repo/m2-snapshot-repository/org/apache/myfaces/tobago/tobago-example-blank/
=== Tobago and MyGourmet
To get a glimpse of Tobago , let's take a look at the already popular MyGourmet application . Illustration Tobago and MyGourmet shows a Tobago created website of the application.
 
Figure: Tobago and MyGourmet
Web application developers are facilitated by the use of Tobago to create a front end by not having to deal with a variety of different technologies, but can focus only on a framework. 
Listing page declaration with Tobago and Facelets shows a section of the file used for page creation customer.xhtml . No HTML was used for the page description using Tobago and the general layout of the page was governed only by specifying the existing rows or columns and a respective size definition. On the possible definitions and their meaning is discussed in the section [subsec grid layout] received.
 <tc:tabGroup switchType="reloadTab">
  <tc:tab label="#{msgs.title_show_customer}">
    <tc:panel>
      <f:facet name="layout">
        <tc:gridLayout rows="fixed;fixed;..."/>
      </f:facet>
      <tx:in label="#{msgs.first_name}" required="true"
          value="#{customerController.customer.firstName}"/>
      ....
      <tx:selectBooleanCheckbox label="#{msgs.use_credit_card}"
          value="#{customerController.customer.useCreditCard}">
        <f:facet name="change">
          <tc:command action=
              "#{customerController.changeCreditCardUsage}"/>
        </f:facet>
      </tx:selectBooleanCheckbox>
      ...
      <tc:cell/>
        <tc:panel>
          <f:facet name="layout">
            <tc:gridLayout columns="*;fixed;fixed"/>
          </f:facet>
          <tc:cell/>
          <tc:button label="#{msgs.cancel}" immediate="true"
              action="#{customerController.cancel}"/>
          <tc:button label="#{msgs.save}" transition="true"
              action="#{customerController.saveCustomer}"/>
        </tc:panel>
      </tc:panel>
  </tc:tab>
  <tc:tab label="#{msgs.title_addresses}">
    ...
  </tc:tab>
</tc:tabGroup>
To port existing applications to Tobago , only a few steps are necessary. Only a few adjustments have been made in the MyGourmet application to convert it to Tobago . Using the previous services, the following changes were made in addition to the page description:
web.xml
In the web.xml the resource servlet of Tobago was entered. The resource servlet is used to load CSS, JS, and graphics. The specification of the resource servlet is required in case the resources are included as a library. For unpacked resources, however, the specification is not necessary. Listing Resource servlet in the web.xml shows the declaration of a resource servlet within the web.xml .
 <servlet>
  <servlet-name>ResourceServlet</servlet-name>
  <servlet-class>
    org.apache.myfaces.tobago.servlet.ResourceServlet
  </servlet-class>
</servlet>

<servlet-mapping>
  <servlet-name>ResourceServlet</servlet-name>
  <url-pattern>
    /org/apache/myfaces/tobago/renderkit/*
  </url-pattern>
</servlet-mapping>
faces-config.xml 
Tobago does not support JSF 2.0 in version 1.0.x and thus no implicit navigation. Therefore, we have to enter the navigation rules necessary for navigation in MyGourmet in the faces-config.xml . The services already defined via annotations in Spring can be used without any changes.
Finally, the configuration file tobago-config.xml must be created. In the tobago-config.xml (see listing configuration in the tobago-config.xml ) the theme to be used and the resource directory are entered.
 <tobago-config>
  <theme-config>
    <default-theme>speyside</default-theme>
  </theme-config>
  <resource-dir>tobago-resource</resource-dir>
  <resource-dir>
    org/apache/myfaces/tobago/renderkit
  </resource-dir>
</tobago-config>
As an introduction to the development of a web application with Tobago as a JSF framework, the basic setup already mentioned in section [Section: Tobago - an overview] can be used. It contains all the necessary configuration files for the initial creation of a project. 
In the following, we will discuss some of the controls used in Figure Tobago and MyGourmet .
=== Tobago controls
In general Tobago offers two libraries tc and tx for the declaration of controls. The tc library contains the pure controls, while the tx library contains compositions from controls. For example, a tx control is often a composition of the actual control and a label.
==== Tobago tc: in / tx: in
A single-line input field is represented by a tc: in . As an extension to this input field Tobago offers the tx: in . This extension includes a label next to the input field. Listing The tx: in-Tobago control shows how to use the tx: in . The label is bound to the input field and with a click on the label the input field receives the focus.
 <tx:in
  label="First Name"
  value="#{customerController.customer.firstName}"
  required="false" readonly="false"
  disabled="false" rendered="true" />
The underlying theme sets the width of the label. However, you can adjust this width using the labelWidth attribute . Also, access keys are supported. If the label specified in the page description contains an underscore, the following letter is defined as an access key. On the page shown, the access key is now marked as an underlined letter.
==== Tobago UICommand
Tobago offers several ways to support command components. The basic controls for this are the tc: button and the tc: link . Other controls include the tc: menu and the tc: toolbar , which we will discuss in more detail in the next sections.
 <tc:button label="Delete Customer" defaultCommand="false"
    action="#{customerController.delete}"
    image="image/delete.png" transition="false">
  <f:facet name="confirmation">
    <tc:out value="Do you want to delete the customer?" />
  </f:facet>
</tc:button>
In Listing The tc: button-Tobago-Control displays the declaration of a tc: button . The action attribute describes the function that should be executed when clicking on the button. In addition, the tc: button -Control can be decorated with a picture. The image can be loaded either via the path, relative to the root of the web application, or via the Resource Manager of Tobago . 
The facet confirmation ensures that the action is only executed when the confirmation message has been confirmed by the user with an 'OK'. The transition attribute, by default true , causes the page to be locked for the duration of the action. The page is darkened for the time of the action to be taken and an hourglass is displayed. Implicitly achieved by this procedure is that an action by repeatedly clicking on a button is not performed more often than desired. A conceivable scenario would be to delete a customer from the application MyGourmet . If the deletion of a customer takes a longer period of time, and a user clicks the delete button again, this could lead to an error message because the customer is already deleted. Is the attribute defaultCommand with the value true The action linked to this button is also executed after pressing the return key. 
The Tobago-Control tc: command can be used, for example, to react to events. Listing The tc: command Tobago control shows the event handling declaration used in the MyGourmet application.
 <tx:selectBooleanCheckbox label="Use CC"
    value="#{customerController.customer.useCreditCard}">
  <f:facet name="change">
    <tc:command
        action="#{customerController.changeCreditCardUsage}"/>
  </f:facet>
</tx:selectBooleanCheckbox>
==== Tobago tc: tabGroup
The Tobago-Control tc: tabGroup offers the possibility to display content on different tab panels. The change between the individual panels takes place via the tab tabs. Illustration The tc: tabGroup Tobago control shows the tc: tabGroup control used in MyGourmet on the customer side .
 
Figure: The tc: tabGroup Tobago control
The loading behavior of the individual tab panels is controlled by the switchType attribute . Possible values ​​are here:
client If the value client is used for switchType , all data for the individual tab panels is written to the HTML output when the page is created. After the page has been loaded on the client, switching between the individual tab panels is faster, but the HTML can become very large depending on the content being displayed. The value client is the default value. 
reloadTab If the contents are to be loaded only when the tab panel is actually displayed, the value reloadTab can be used. If the tab panel is selected, the content will be requested by the server and the tab panel will be updated via Ajax.
reloadPage Even with the value reloadPage , the content of the individual tab panels is only loaded when the tab panel is to be displayed. However, unlike the reloadTab, the entire page is reloaded.
==== Tobago tc: menu
A certain amount of functionality is often offered by menus in desktop applications. The Tobago-Control tc: menu displays a menu on a page. Listing The tc: menu Tobago control shows a section of the declaration of the control.
 <tc:page>
...
  <f:facet name="menuBar">
    <tc:menuBar>
      <tc:menu label="Sections">
        <tc:menuItem label="Customers"
            action="customer-list"
            immediate="true"
            image="resources/images/16/customer.png"/>
        <tc:menuItem label="Providers"
            action="provider-list"
            immediate="true"
            image="resources/images/16/provider.png"/>
      </tc:menu>
      ...
    </tc:menuBar>
  </f:facet>
  ...
<tc:page>
A menu is added to a page via the Facet menuBar of a tc: page . Menu entries can be created by the tags tc: menuItem , tc: menuCheckBox and tc: menuRadio . A separator between individual menu entries is inserted by a tc: separator .
==== Tobago tc: toolBar
The tc: toolBar -Control is used to render a group of buttons. As shown in Figure The tc: toolBar-Tobago-Control , there is the possibility to provide the individual buttons with a label or an image.
 
Figure: The tc: toolBar-Tobago-Control
An image can be used in different standard sizes. The size of the image to be displayed is determined by the iconsize attribute . Valid values ​​for this attribute are big , small, and off . Individual buttons are created by a tc: toolBarCommand . If, for example, an image is to be greyed out, this option exists via the attribute disabled . If the condition specified in this attribute is met, the resource manager attempts to load an image using the following naming scheme:
Normal image - images / edit.png
Grayed out image - images / editDisabled.png
Listing declaration of the tc: toolBar-Tobago control shows the declaration of a tc: toolBar control .
 <tc:toolBar>
  <tc:toolBarCommand 
    label="Add Customer"
    action="customer"
    image="resources/images/new.png"/>
  <tc:toolBarCommand
    label="Edit Customer"
    action="#{customerController.editCustomer}"
    image="resources/images/edit.png"
    disabled="#{customerController.customerAvailable}"/>
</tc:toolBar>
==== Tobago tc: sheet
Tables are created in Tobago with the tag tc: sheet . In the Tobago - MyGourmet example, a table is used to display the addresses of customers. Listing The tc: sheet Tobago control shows a section of the declaration of a table.
 <tc:sheet var="address"
    value="#{customerController.addressList}"
    state="#{customerController.selectedAddress}">
  <tc:column label="Zip Code">
    <tc:out value="#{address.zipCode}"/>
  </tc:column>
  <tc:column label="City">
    <tc:out value="#{address.city}"/>
  </tc:column>
  ...
</tc:sheet>
The var attribute accesses the objects of the list specified at runtime at runtime, as specified in the value attribute. This list contains the data to be displayed in the tc: sheet . Access to instance variables or methods is done by simple dot notation. Columns are added within the tc: sheet via the tc: column tag . In Listing The tc: sheet Tobago control uses a tc: out in each column to display each address value. However, you can also use the tags tc: in , tc: selectOneChoice or tc: selectBooleanCheckbox be used in a column. The various attributes starting with show control the navigation behavior of a table. Thus, the attribute showDirectLinks can jump directly to a desired page in the table. The state attribute is used to get current information about the table. The method specified by method-binding must be able to receive a SheetState as the transfer parameter . For example, the selected line can now be determined via this object. This allows a developer to respond to user events. In MyGourmet The user can delete a selected address via the toolbar by clicking Delete Address . The deleteAddress method to be executed in the business logic is displayed in the listing selection of a line in the tc: sheet Tobago control .
 public String deleteAddress() {
  Address address = getSingleSelectedAddress();
  if (address != null) {
    customerService.deleteAddress(address);
  }
  return CUSTOMER;
}

private Address getSingleSelectedAddress() {
  List<Integer> selection = selectedAddress.getSelectedRows();
  if (selection.size() != 1) {
    createFacesMessage(FacesMessage.SEVERITY_ERROR,
        "Please select exactly one row.");
    return null;
  }
  return addressList.get(selection.get(0));
}
The sortable attribute of the tc: column activates the sorting of individual columns. If sorting requires its own sorting algorithm, it can be executed via the sortActionListener attribute in the tc: sheet tag. Information about the currently used sorting can also be found in the SheetState .
=== Partial Rendering with Tobago
Performance has always been an important topic in web applications. In order not to completely re-render a page for every request, there is the possibility to reload only individual elements. Tobago also supports this partial rendering. In contrast to the already mentioned tc: tabGroup -Control , where the load behavior is controlled by the switchType attribute, the partial rendering is configured for container controls, such as tc: panel , tc: box , tc: popup or tc: sheet , about the tag tc: attribute . Listing partial rendering in Tobago shows a possible declaration of partial rendering within a tc: box control .
 <tc:page id="page">
  <tc:box label="Container" id="box">
    <tx:selectBooleanCheckbox label="Use Credit Card"
      value="#{controller.useCC}">
      <f:facet name="change">
      <tc:command>
        <tc:attribute name="renderedPartially"
          value=":page:box"/>
      </tc:command>
      </f:facet>
    </tx:selectBooleanCheckbox>
    <tx:in label="Credit Card Number"
        rendered="controller.showCCNumber"/>
  </tc:box>
</tc:page>
The new elements to be loaded are specified via a comma-separated list of ID paths. Using the ID path specified in Listing Partial Rendering in Tobago , you can see the composition of such paths. Each ID path uses the IDs to describe the path to the element to be re-rendered. As with JSF 2.0, updating the controls to be reloaded in the component tree is done only partially. In Listing Partial Rendering in Tobago , the valid ID path is : page: box . The tc: box control is now always re-rendered if the checkbox is selected or deselected. 
The tc: panel-Control can also be reloaded periodically. The facet reload can be used to specify a reload frequency. Listing Periodic reload of the tc: panel control shows an excerpt of the declaration of a reload- facet.
 <tc:panel>
  <f:facet name="reload">
    <tc:reload frequency="5000"/>
  </f:facet>
  ...
</tc:panel>
=== Layout in Tobago
As already mentioned, the layout in Tobago is regulated by a layout manager. The page layout is defined only by the specification of so-called layout tokens for the row and column sizes. However, the definition of the size is not necessary for all controls since, for example, for the input field tc:, there is an already committed size. The information about the already defined sizes of some controls can be found in the file tobago-theme-config.properties of the used theme. Tobago is
currently using the grid layout. The declaration of a layout and the possible layout tokens are described in section [subsec grid layout] treated.
==== Grid layout
The grid layout is used in Tobago to represent the controls specified in the page description. There are five layout containers in Tobago, each of which can receive a facet to define the layout manager:
tc: page
tc: panel
tc: box
tc: popup
tc: tab
Listing layout definition in Tobago shows such a layout definition in Tobago.
 <tc:gridLayout rows="100px;fixed;*"/>
The layout manager divides the available area into a grid. The number of horizontal and vertical fields is determined by the rows and columns. To define a three-line grid, as in the listing layout definition in Tobago , you must pass a semicolon- delimited list of three entries to the rows attribute. Permissible values ​​here are a fixed pixel specification, a fixed or a *. Listing Extended layout definition in Tobago shows a more complex example of a layout definition. 
Let's say the layout manager is tc: panel for the layout container used here 400px, the image to be inserted is assigned 100 pixels and the input field the size defined for the tc: in control . The text field is finally assigned the available remainder. The grid created by the Layout Manager is shown in the illustration Grid created by the Layout Manager .
 <tc:panel>
  <f:facet name="layout">
    <tc:gridLayout rows="100px;fixed;*"/>
  </f:facet>
  <tc:image ... />
  <tc:in ... />
  <tc:textarea ... />
</tc:panel>
 
Figure: Grid created by the Layout Manager
The positioning of the individual controls thus takes place on the basis of the respectively defined row or column sizes. It should be noted that not all definitions are compatible with each other. For the layout token fixed , the size is determined by the defined size of the control in the row or column (bottom-up). This control can also be a layout container. For this layout container a new layout can be determined. However, the layout definition may not contain * since the overlying container would then be unable to return an already defined size. 
By specifying a fixed pixel size or * for the inner one However, this restriction can be bypassed by layout containers because these layout definitions are used to determine the size of the layout from the outer to the inner layout container (top / down). Table tab: layout-def shows possible combinations in the layout definition. For example, if there is a need to connect rows or columns together, the spanX and spanY attributes are available for this layout definition . 
Listing Advanced Layout Definition in Tobago uses the tc: textarea tag . The layout token * specified in the layout definition becomes the tc: textarea the remaining space on the page to be displayed assigned. With an available size of 400px, this means that the remaining 280px will be assigned to the tc: image 100px, the tc: to the size of 20px given by the current theme and the tc: textarea . However, if you want to display only the two controls tc: image and tc: in on the page , they both have a fixed size, leaving a rest of 280px. As a filling element in Tobago , the tc: cell -Control can be used here to occupy this remaining area.
Layout token	in sublayout included definition	Evaluation by layout manager
fixed	any fixed and px, no *	correctly
fixed	at least one *	not correct, the layout manager can not calculate the fixed value
px	any fixed and px, no *	may not be correct, individual values ​​are interdependent. A developer must determine the individual sizes correctly
px	at least one *	correctly
{*}	any fixed and px, no *	may not be correct, too little space will show a scrollbar, too much space will stretch controls
{*}	at least one *	correctly
=== Themes and Markup
Tobago emphasizes the separation of appearance and structure. The developer defines in the page description on an abstract level which controls should be on a page and how they should relate to each other.
==== Themes in Tobago
The theme determines how the controls are displayed. The theme controls visual properties such as colors, sizes and fonts. Furthermore, the theme determines which technology should be used for the presentation. Currently, the themes delivered only support HTML as the view technology. 
Tobago currently contains four themes: Scarborough , Speyside , Richmond and Charlotteville .
 
Picture: Tobago Themes
These were named after places on Tobago . Scarborough is the basic theme that tries to solve most control features with standard HTML. Speyside is based on this theme and offers a nice and current look and feel. The Themes Richmond and Charlotteville are by and large just color variations from the Speyside theme. Such modified themes can be done by analogy to Richmond and Charlotteville and with some CSS understanding.
A theme offers the possibility to create uniform masks. As a page developer you have no direct influence on the design of the page. This way the pages fit better into the corresponding applications. With a customized theme, a consistent corporate design can be easily achieved. 
It is possible to change the themes at runtime. Thus, each user can choose according to their own taste a suitable theme. On the other hand, this makes it possible to implement a multi-client application. Depending on the brand or customer, a specific theme with matching colors and logos can be used.
==== Resource Management in Tobago
Themes can build on each other. Resources that a theme itself does not provide are used by the underlying theme. These resources include images, stylesheets , JavaScript files, and string resources. A resource is selected depending on the locale, browser and theme. The resource manager goes through all registered resource directories and tries to find a resource that matches the locale, browser and theme. Then the search is repeated with the fallback locales, later the search is repeated first with the fallback browsers and then with the fallback themes. The result of the search is cached for later reuse. Here is a simplified example of the search order:
...\html\html\speyside\speyside\mozilla\mozilla\image\image\country_de_DE.gif
...\html\html\speyside\speyside\mozilla\mozilla\image\image\country_de.gif
...\html\html\speyside\speyside\mozilla\mozilla\image\image\country.gif
...\html\html\speyside\speyside\standard\standard\image\image\country_de_DE.gif
...\html\html\speyside\speyside\standard\standard\image\image\country_de.gif
...\html\html\speyside\speyside\standard\standard\image\image\country.gif
...\html\html\scarborough\scarborough\mozilla\mozilla\image\image\country_de_DE.gif
...\html\html\scarborough\scarborough\mozilla\mozilla\image\image\country_de.gif
...\html\html\scarborough\scarborough\mozilla\mozilla\image\image\country.gif
...\html\html\scarborough\scarborough\standard\standard\image\image\country_de_DE.gif
...\html\html\scarborough\scarborough\standard\standard\image\image\country_de.gif
...\html\html\scarborough\scarborough\standard\standard\image\image\country.gif
...\html\html\standard\standard\mozilla\mozilla\image\image\country_de_DE.gif
...\html\html\standard\standard\mozilla\mozilla\image\image\country_de.gif
...\html\html\standard\standard\mozilla\mozilla\image\image\country.gif
...\html\html\standard\standard\standard\standard\image\image\country_de_DE.gif
...\html\html\standard\standard\standard\standard\image\image\country_de.gif
...\html\html\standard\standard\standard\standard\image\image\country.gif
For images, the resource manager stops the search at the first find. For other resources such as stylesheets and scripts, the Resource Manager returns all finds in a list, in the order in which they were searched. This search mechanism forms the basis for the defaulting mechanism of the theme management.
Using the Resource Manager, the developer can provide localized images. This is necessary if the pictures contain texts - for example for pictures on buttons. The Resource Manager supports the standard string resource XML format, which simplifies the use of special characters. Themes can also support corporate wordings - each theme can specify, for example, which variant should be used for specific terms, such as email, e-mail or e-mail, in the associated corporate design. 
In the tobago-config.xmlFile, additional directories can be registered with the Resource Manager. These have priority in finding resources and can therefore be used to override or supplement existing resources. Unfortunately, no API has yet been defined for Themes in Tobago. Changes at this level may therefore cause compatibility issues in newer versions of Tobago .
 <tobago-config>
  ...
  <resource-dir>tobago-resources</resource-dir>
  ...
</tobago-config>
The resource directory describes a directory within the WAR archive relative to the root directory. Below the resource directory, the paths have the following structure:
<content-type>/<theme>/<browser>/<directory>
    /<resource-name>(_<locale>)?.<extension>
==== Markup in Tobago
With markup controls are enriched by logical markers with semantic meta-information. Which markup values ​​a theme supports is in its theme-config.xml file. If a theme does not define markup values ​​for a renderer, the renderer inherits the values ​​of the fallback theme. 
The included themes support the following markup values:
number for <tc: in> and <tc: out >
strong for <tc: out>
deleted for <tc: out>
The markup value number is used to format numbers. Such numbers are usually right justified. The value strong serves as a highlight and is shown bold in the delivered themes. The value deleted marks content as deleted and is often shown as crossed out. In general, the presentation is controlled by the respective theme and therefore fits the look and feel of the theme. 
Markup can be easily extended. For this purpose, a separate theme can be written or a markup directly defined in the application's tobago-config.xml file. Listing Markup new for Sheet cell shows usage in the page declaration.
 <tc:column label="Name"
    markup="#{customerController.newCustomer == customer 
        ? 'new' : ''}">
  <tc:out value="#{customer.fullName}"/>
</tc:column>
In the Tobago variant of MyGourmet newly added customers are highlighted with the markup new in the customer list. The new markup value new is provided in the tobago-config.xml file (see Listing resource directory in tobago-config.xml ).
 <tobago-config>
  <renderers>
    <renderer>
      <name>Column</name>
      <supported-markup>
        <markup>new</markup>
      </supported-markup>
    </renderer>
  </renderers>
  ...
</tobago-config>
To control the visualization, you can add CSS information to a particular CSS style class, resulting in the renderer and markup value as follows:
"tobago-" + StringUtils.uncapitalize(rendererType) 
    + "-markup-" + markupName
This style class can then be defined in a suitable CSS file that can be found by the resource manager. The Resource Manager rules specify the path to which the CSS "~ file should be reachable, and for the markup value new , the CSS will be in the file
.../webapp/tobago-resources/html
    /scarborough/standard/style/style.css
placed. Here is the CSS definition for markup new in style.css :
.tobago-column-markup-new {
  background-color: lightyellow;
}
In addition, renderers can be enhanced to realize new markup values ​​in a form that can not be accomplished by CSS-only changes. Examples are in tobago-theme-example in the Tobago- Trunk ( http://svn.apache.org/repos/asf/myfaces/tobago/trunk/tobago-example/ ).
=== Summary and Outlook
Tobago allows you to create web applications using a variety of controls. The development is simple and requires no further knowledge in HTML or CSS. The use of Ajax is implicitly supported. The layout is managed in Tobago by a layout manager, so no HTML framework needs to be used to position individual controls. The layout definition is based on clear rules and follows a well-defined scheme. With Tobago can be set up even the most complex-looking websites in no time due to this approach. Prototyping can also be done without the need for a working backend. 
The documentation on the TobagoProject page at http://myfaces.apache.org/tobago/documentation.html allows developers to quickly get started on developing with Tobago . A compatibility matrix of supported servers, containers and libraries on the website completes the package. 
The development of Tobago aims in the future to support the JSF 2.0 standard. The integration of external JSF frameworks like Tomahawk should also be enabled. A detailed overview can also be found on the project page.