== A short introduction to Maven

Apache Maven is a very useful tool for managing Java-based projects. Among other things, it can manage applications, create, distribute, automatically test, manage dependencies and create web pages of the project. In addition to a standardized description of projects in the Project Object Model ( pom.xml ) and a standardized build process, Maven offers, among other things, an automatic resolution of dependencies on other projects and libraries. The functionality can be extended by a variety of plug-ins, some of which we will show later. 

First, you should know that Maven All files required for the build process, be they normal libraries or plug-ins, are automatically downloaded from central Internet sites - the so-called Maven repositories - The central Maven repository can be found, for example, at http: // search .maven.org / . There you can also easily search for Maven artifacts .: . In such a repository , the libraries of many open-source projects are stored in a special Maven structure (subdivided by Group-ID, Artifact-ID and version). 

A big plus point of Maven is the automatic management of dependencies on libraries. The dependencies of a project are defined in its pom.xml in the form of dependency elements. Listing Maven dependency for MyFaces 2.2.1 shows the dependencies for MyFaces in version 2.2.1.

<dependencies>
  <dependency>
    <groupId>org.apache.myfaces.core</groupId>
    <artifactId>myfaces-api</artifactId>
    <version>2.2.1</version>
    <scope>compile</scope>
  </dependency>
  <dependency>
    <groupId>org.apache.myfaces.core</groupId>
    <artifactId>myfaces-impl</artifactId>
    <version>2.2.1</version>
    <scope>compile</scope>
  </dependency>
</dependencies>

As you can see, dependencies on libraries are defined by their Group ID, Artifact ID, and Version. The repository reflects this structure in the directory hierarchy. 

The required libraries are stored after loading in a local repository and can be obtained from there if required. By default, this local directory is in the user's home directory, which may vary depending on the operating system. For example, on Windows, the local repository resides in the following directory:
C:\Benutzer\Benutzer\Benutzername.m2\Benutzername.m2\repository
repository
=== Installing Maven

In this section we describe step by step how to set up Maven on a Windows system:

Loading Maven
A compressed file of the current version of Maven can be found on the project website http://maven.apache.org . The current version is 3.0.5, with which all examples were tested.
Unpacking the archive
First you have to extract the downloaded zip file apache-maven-3.xx-bin.zip into a directory of your choice. In the further course, we assume the following directory, which may look different depending on the specific version number on your computer:
C:\Programme\Programme\maven-3.x.x
Setting the Environment
Variables Needed To run Maven properly, some environment variables must be set. First we set the variable MAVEN_HOME to the installation directory of Maven. Open to it
Systemeinstellungen (Windows-Taste + Pause)
    -> Erweitert -> Umgebungsvariablen
and add a variable with the name MAVEN_HOME and the following value among the user variables :
C:\Programme\Programme\maven-3.x.x
Furthermore, the bin directory of the Maven installation must be included in the system path. Set the user variable PATH to the following value:
MAVEN_HOME\bin;PATH
In the same dialog, JAVA_HOME must also be set to the Java JDK path, for example:
C:\Programme\Programme\Java\Java\jdk1.7.0_21
Checking Maven The console can now be checked to see if Maven has been set up correctly:
mvn --version
If a version number is issued, the next step can be taken; if not, the previous points must be checked again for correctness.
Your system now has a working version of Maven . As entry points for more in-depth information about Maven you can visit the project page http://maven.apache.org and the freely available books Maven: The Complete Reference and Maven by Example Maven by Example and Maven: The Complete Reference at http: / /www.sonatype.com/resources/books .: .
=== Maven and MyGourmet
All MyGourmet examples are designed as Maven projects, making them very easy to use. In this section we will briefly present the possibilities of Maven based on MyGourmet . The source code for all MyGourmet examples is available at the URL http://jsfatwork.irian.at . 
Let's start with the most basic task: The build process of the project is triggered with the following command in the root directory of the project:
mvn clean install
Maven then deletes all previously generated files, compiles all classes, and puts them in a WAR archive, along with any resources and libraries defined by dependencies in the pom.xml file . These files end up in the directory target in the first step . The WAR archive is then stored in the local repository under the Group ID, the Artifact ID, and the version specified in the pom.xml . For the example MyGourmet 1, this results in the directory tree shown in Figure MyGourmet 1 in the local repository .
 
Figure: MyGourmet 1 in the local repository
By default, all MyGourmet examples use Mojarra as a JSF implementation. However, we have designed the project description in the file pom.xml so that you can switch to myFaces without any changes to the file itself . There are two profiles with the dependencies required for the implementation. If you do not explicitly select any of the profiles, Mojarra will always be used. If you want to use MyFaces , you must activate the profile with the ID myfaces as follows when calling Maven :
mvn clean install -P myfaces
If you encounter problems with the browser running MyFaces and Mojarra in the same project (or vice versa), you should clear the browser's cache. Sometimes cached JavaScript files can cause problems in this case. 
All MyGourmet examples are configured via their pom.xml so that they can be executed with the following command in the root of the project:
mvn jetty:run
The Jetty Maven plug-in then starts the Jetty servlet container and rolls out the application. MyGourmet 1 can then be called in the browser at the following address, for example:
http://localhost:8080/mygourmet01
You do not have to compile the project or install it in the local repository. Maven will automatically take care of it, if that has not happened yet. 
Again, you can enable Apache MyFaces via the profile with the ID myfaces :
mvn jetty:run -P myfaces
All current development environments now support the direct import of Maven projects. How this works in detail with Eclipse, you can read in section Section: Eclipse and MyGourmet .
=== Creating a JSF project
With Maven , it is very easy to get a Hello World to generate application. For this purpose, in Maven there is the concept of the so-called archetypes . These are templates on the basis of which existing libraries can be used to generate Maven projects with the basic structure of an application. 
The template catalog of MyFaces currently contains the following eight archetypes for generating JSF projects:
MyFaces-Hello-World
template for the basic framework of a project with MyFaces in version 1.2 including all dependencies and JSP as page declaration language.
MyFaces-Hello-World with Facelets
Template for the basic framework of a project with MyFaces in version 1.2 including all dependencies and facelets as page-declaration language.
MyFaces-Hello-World with Portlets
Template for the framework of a Portlets project with MyFaces in version 1.2 including all dependencies and JSP as the page-declaration language.
MyFaces-Hello-World 2.0
Template for the basic framework of a project with MyFaces in version 2.1 including all dependencies and facelets as page-declaration language.
MyFaces-Hello-World 2.0 with OWB
Template for the framework of a project with MyFaces in version 2.1 and Apache OpenWebBeans Apache OpenWebBeans is an implementation of the Contexts and Dependency Injection for Java (CDI, JSR-299) standard : including all dependencies and facelets page declaration language.
JSF component
A custom template that can be used to generate Maven projects for component libraries using MyFaces version 1.2.
MyFaces Hello World with Trinidad
Template for the framework of a Maven project with MyFaces in version 1.2 and Trinidad in version 1.2 including all dependencies and JSP as the page declaration language.
MyFaces-Hello-World with Trinidad 2.0
Template for the basic structure of a Maven project with MyFaces in version 2.1 and Trinidad in version 2.0 including all dependencies and facelets as page-declaration language.
Let's create a Maven project for a simple web application in JSF. The process is very simple: To do this, call the following command in the console in any directory:
mvn archetype:generate 
    -DarchetypeCatalog=http://myfaces.apache.org
This command starts the project generation with the template catalog of Apache MyFaces . Creating the project consists of the following three steps:
Maven displays all the templates from the above catalog http://myfaces.apache.org in a numbered list. Select the number of the template named myfaces-archetype-helloworld20 .
After the selection, you must configure the application. For the group ID, enter at.irian.jsfatwork , as artifact-ID helloworld , as version 1.0-SNAPSHOT and as package of the project at.irian.jsfatwork.helloworld .
After confirming the settings, Maven creates the project structure under the directory / helloworld .
The generated application builds on MyFaces in version 2.1 with all required dependencies - these have already been entered in the Maven project file pom.xml . Likewise are under
\helloworld\helloworld\src\src\main\main\webapp\webapp\WEB-INF
the configuration files web.xml and faces-config.xml needed for the application with the required parameters. Depending on requirements, these are to be modified as described in section Section: Configuration of JavaServer Faces .
